[telegram]
Enabled="true"
Token="8596622001:AAHpu4ebqENpJeaiBmQi_SxRlT06NSEzWRE"
RemoteNickFormat="<${NICK}>"

[whatsapp]
Enabled="true"
Name="RenderBridge"
DataDir="./data"

[[gateway]]
Name="whatsapp-telegram-bridge"
Enable=true
Inbound="telegram.telegram.-4697100211"
Outbound="whatsapp.whatsapp.ID_ВАШЕЙ_ГРУППЫ_WHATSAPP"
